<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class TagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['name' => 'Average Male Body', 'name_zh' => '普通男性体型'],
            ['name' => 'European', 'name_zh' => '欧洲人'],
            ['name' => 'Blond Hair', 'name_zh' => '金发'],
            ['name' => 'Short Hair', 'name_zh' => '短发'],
            ['name' => 'Big Dick', 'name_zh' => '大阴茎'],
            ['name' => 'Dress', 'name_zh' => '连衣裙'],
            ['name' => 'Bubble Butt', 'name_zh' => '翘臀'],
            ['name' => 'Piercing', 'name_zh' => '穿孔'],
            ['name' => 'Tattoo', 'name_zh' => '纹身'],
            ['name' => 'Athletic', 'name_zh' => '健美'],
            ['name' => 'German', 'name_zh' => '德国人'],
            ['name' => 'Black Hair', 'name_zh' => '黑发'],
            ['name' => 'High Heels', 'name_zh' => '高跟鞋'],
            ['name' => 'Bald Pussy', 'name_zh' => '剃毛阴部'],
            ['name' => 'Innie Pussy', 'name_zh' => '内收型阴部'],
            ['name' => 'Big Tits', 'name_zh' => '大胸'],
            ['name' => 'Enhanced', 'name_zh' => '整形增强'],
            ['name' => 'Sex', 'name_zh' => '性爱'],
            ['name' => 'Cum on Tits', 'name_zh' => '射在胸上'],
            ['name' => 'Cum Shot', 'name_zh' => '射精镜头'],
            ['name' => 'Facial', 'name_zh' => '面部射精'],
            ['name' => 'Feet', 'name_zh' => '脚'],
            ['name' => 'Fetish', 'name_zh' => '恋物癖'],
            ['name' => 'Footjob', 'name_zh' => '足交'],
            ['name' => 'Handjob', 'name_zh' => '手交'],
            ['name' => 'Kissing', 'name_zh' => '接吻'],
            ['name' => 'Masturbation', 'name_zh' => '自慰'],
            ['name' => 'Sneaky', 'name_zh' => '偷偷摸摸'],
            ['name' => 'Squirt', 'name_zh' => '潮喷'],
            ['name' => 'Anal Fingering', 'name_zh' => '肛门手指插入'],
            ['name' => 'Blowjob', 'name_zh' => '口交'],
            ['name' => 'Deep Throat', 'name_zh' => '深喉'],
            ['name' => 'Face Fuck', 'name_zh' => '面交'],
            ['name' => 'Fisting', 'name_zh' => '拳交'],
            ['name' => 'Gagging', 'name_zh' => '作呕'],
            ['name' => 'Pussy Fingering', 'name_zh' => '阴部手指插入'],
            ['name' => 'Pussy Licking', 'name_zh' => '舔阴'],
            ['name' => 'Spanking', 'name_zh' => '打屁股'],
            ['name' => 'Indoors', 'name_zh' => '室内'],
            ['name' => 'Kitchen', 'name_zh' => '厨房'],
            ['name' => 'Anal', 'name_zh' => '肛交'],
            ['name' => 'cheating', 'name_zh' => '出轨'],
            ['name' => 'Couples Fantasies', 'name_zh' => '情侣幻想'],
            ['name' => 'Doggystyle', 'name_zh' => '后入式'],
            ['name' => 'Doggystyle - Standing', 'name_zh' => '站立后入式'],
            ['name' => 'Missionary', 'name_zh' => '传教士体位'],
            ['name' => 'Side Fuck', 'name_zh' => '侧入式'],
            ['name' => 'Anal Toys', 'name_zh' => '肛门玩具'],
            ['name' => 'Sex Toys', 'name_zh' => '性玩具'],
            ['name' => 'Top Ad', 'name_zh' => '顶部广告'],
            ['name' => '4k', 'name_zh' => '4K'],
            ['name' => 'American Man', 'name_zh' => '美国男性'],
            ['name' => 'Caucasian', 'name_zh' => '白人'],
            ['name' => 'Brunette', 'name_zh' => '褐发女郎'],
            ['name' => 'Store Clerk', 'name_zh' => '店员'],
            ['name' => 'Trimmed Pussy', 'name_zh' => '修剪过的阴部'],
            ['name' => 'Cumshot Clean-Up', 'name_zh' => '射精清理'],
            ['name' => 'Store', 'name_zh' => '商店'],
            ['name' => 'Work Fantasies', 'name_zh' => '工作幻想'],
            ['name' => 'Ballerina', 'name_zh' => '芭蕾舞者'],
            ['name' => 'Cowgirl', 'name_zh' => '女上位'],
            ['name' => 'Vibrator', 'name_zh' => '振动器'],
            ['name' => 'Grey', 'name_zh' => '灰色'],
            ['name' => 'Muscular Man', 'name_zh' => '肌肉男'],
            ['name' => 'Brown Hair', 'name_zh' => '棕发'],
            ['name' => 'Black Male', 'name_zh' => '黑人男性'],
            ['name' => 'Big Ass', 'name_zh' => '大屁股'],
            ['name' => 'Thick', 'name_zh' => '丰满'],
            ['name' => 'Voluptuous', 'name_zh' => '丰腴'],
            ['name' => 'Red Head', 'name_zh' => '红发'],
            ['name' => 'Huge Tits', 'name_zh' => '超大胸'],
            ['name' => 'Fishnet', 'name_zh' => '渔网袜'],
            ['name' => 'Panty Hose', 'name_zh' => '连裤袜'],
            ['name' => 'Gangbang', 'name_zh' => '轮奸'],
            ['name' => 'Orgy', 'name_zh' => '群交'],
            ['name' => 'Bukkake', 'name_zh' => '颜射群射'],
            ['name' => 'Blowjob - Double', 'name_zh' => '双人口交'],
            ['name' => 'Blowjob - POV', 'name_zh' => '主观口交'],
            ['name' => 'Blowjob - Threeway', 'name_zh' => '三人口交'],
            ['name' => 'Face Sitting', 'name_zh' => '面坐'],
            ['name' => 'Titty Fuck', 'name_zh' => '乳交'],
            ['name' => 'Bedroom', 'name_zh' => '卧室'],
            ['name' => 'Party', 'name_zh' => '派对'],
            ['name' => 'Ass Worship', 'name_zh' => '臀部崇拜'],
            ['name' => 'Big Tits Worship', 'name_zh' => '大胸崇拜'],
            ['name' => 'Double Penetration - DP', 'name_zh' => '双重插入'],
            ['name' => 'Interracial', 'name_zh' => '跨种族'],
            ['name' => 'Doggystyle Blowjob', 'name_zh' => '后入式口交'],
            ['name' => 'DP BJ', 'name_zh' => '双插口交'],
            ['name' => 'Missionary BJ', 'name_zh' => '传教士体位口交'],
            ['name' => 'Reverse Cowgirl', 'name_zh' => '反向女上位'],
            ['name' => 'Reverse Cowgirl BJ', 'name_zh' => '反向女上位口交'],
            ['name' => 'Scissoring', 'name_zh' => '剪刀式'],
            ['name' => 'Side Fuck BJ', 'name_zh' => '侧入式口交'],
            ['name' => 'Side Rider', 'name_zh' => '侧骑位'],
            ['name' => 'Side Rider BJ', 'name_zh' => '侧骑位口交'],
            ['name' => 'Blonde', 'name_zh' => '金发女郎'],
            ['name' => 'Maid', 'name_zh' => '女仆'],
            ['name' => 'Cleaning', 'name_zh' => '清洁'],
            ['name' => 'Wet', 'name_zh' => '湿润'],
            ['name' => 'Spitting', 'name_zh' => '吐口水'],
            ['name' => 'Rough Sex', 'name_zh' => '激烈性爱'],
            ['name' => 'Soap', 'name_zh' => '肥皂'],
            ['name' => 'Sun Glasses', 'name_zh' => '太阳镜'],
            ['name' => 'Australian', 'name_zh' => '澳大利亚人'],
            ['name' => 'Big Naturals', 'name_zh' => '天然大胸'],
            ['name' => 'Big Boobs (Natural)', 'name_zh' => '天然大乳房'],
            ['name' => 'Natural Tits', 'name_zh' => '天然胸部'],
            ['name' => 'Glasses', 'name_zh' => '眼镜'],
            ['name' => 'Student', 'name_zh' => '学生'],
            ['name' => 'FFM', 'name_zh' => '女女男'],
            ['name' => 'Threesome', 'name_zh' => '三人行'],
            ['name' => 'Cum On Ass', 'name_zh' => '射在臀部'],
            ['name' => 'Cum Swap', 'name_zh' => '交换体液'],
            ['name' => 'Twerking', 'name_zh' => '扭臀舞'],
            ['name' => 'Ass Licking', 'name_zh' => '舔臀'],
            ['name' => 'Tittyfuck - POV', 'name_zh' => '主观乳交'],
            ['name' => 'Library', 'name_zh' => '图书馆'],
            ['name' => 'Public Sex', 'name_zh' => '公共场合性爱'],
            ['name' => 'Fuck n Lick', 'name_zh' => '边做边舔'],
            ['name' => 'Stand And Carry', 'name_zh' => '站立抱持'],
            ['name' => 'Public Flashing', 'name_zh' => '公共裸露'],
            ['name' => 'Slim', 'name_zh' => '苗条'],
            ['name' => 'British', 'name_zh' => '英国人'],
            ['name' => 'Spoon', 'name_zh' => '勺子'],
            ['name' => 'Professional/White Collar', 'name_zh' => '专业人士/白领'],
            ['name' => 'Blouse', 'name_zh' => '女式上衣'],
            ['name' => 'Medium Ass', 'name_zh' => '中等臀部'],
            ['name' => 'Boss', 'name_zh' => '老板'],
            ['name' => 'Outie Pussy', 'name_zh' => '外翻型阴部'],
            ['name' => 'Handjob - POV', 'name_zh' => '主观手交'],
            ['name' => 'Office', 'name_zh' => '办公室'],
            ['name' => 'Reverse Cowgirl - POV', 'name_zh' => '主观反向女上位'],
            ['name' => 'Teacher', 'name_zh' => '老师'],
            ['name' => 'Garter Belt', 'name_zh' => '吊袜带'],
            ['name' => 'Black Stockings', 'name_zh' => '黑色长袜'],
            ['name' => 'French', 'name_zh' => '法式'],
            ['name' => 'Czech', 'name_zh' => '捷克'],
            ['name' => 'Average Dick', 'name_zh' => '普通阴茎'],
            ['name' => 'Small Ass', 'name_zh' => '小屁股'],
            ['name' => 'School Girl', 'name_zh' => '女学生'],
            ['name' => 'Sandals', 'name_zh' => '凉鞋'],
            ['name' => 'Medium Tits', 'name_zh' => '中等胸部'],
            ['name' => '2 on 1 (2 Males)', 'name_zh' => '双男一女'],
            ['name' => 'Oral Train', 'name_zh' => '口交列车'],
            ['name' => 'Classroom', 'name_zh' => '教室'],
            ['name' => 'College', 'name_zh' => '大学'],
            ['name' => 'School', 'name_zh' => '学校'],
            ['name' => 'Compilation', 'name_zh' => '合集'],
            ['name' => 'School Fantasies', 'name_zh' => '学校幻想'],
            ['name' => 'Arch', 'name_zh' => '拱桥体位'],
            ['name' => 'Cowgirl - POV', 'name_zh' => '主观女上位'],
            ['name' => 'Doggystyle - POV', 'name_zh' => '主观后入式'],
            ['name' => 'Missionary - POV', 'name_zh' => '主观传教士体位'],
            ['name' => 'Latin', 'name_zh' => '拉丁裔'],
            ['name' => 'Leggings', 'name_zh' => '紧身裤'],
            ['name' => 'Sports Bra', 'name_zh' => '运动内衣'],
            ['name' => 'Petite', 'name_zh' => '娇小'],
            ['name' => 'Asian', 'name_zh' => '亚洲人'],
            ['name' => 'Thong', 'name_zh' => '丁字裤'],
            ['name' => 'Small Tits', 'name_zh' => '小胸'],
            ['name' => 'Hair Pulling', 'name_zh' => '拽头发'],
            ['name' => 'Booty Shorts', 'name_zh' => '热裤、超短裤或包臀短裤'],
            ['name' => 'T-Shirt', 'name_zh' => 'T恤'],
            ['name' => 'Average Body', 'name_zh' => '普通体型'],
            ['name' => 'Long', 'name_zh' => '长发'],
            ['name' => 'Boyfriends', 'name_zh' => '男友们'],
            ['name' => 'Creampie', 'name_zh' => '体内射精'],
            ['name' => 'Cum On Feet', 'name_zh' => '射在脚上'],
            ['name' => 'Pussy Creampie', 'name_zh' => '阴道内体内射精'],
            ['name' => '69', 'name_zh' => '69式'],
            ['name' => 'Multiple Cum Cleanup', 'name_zh' => '多次清理精液'],
            ['name' => 'Athlete/Jock', 'name_zh' => '运动型男'],
            ['name' => 'Socks', 'name_zh' => '袜子'],
            ['name' => 'Black', 'name_zh' => '黑人'],
            ['name' => 'Foursome', 'name_zh' => '四人行'],
            ['name' => 'Outdoors', 'name_zh' => '户外'],
            ['name' => 'Ass Stacking', 'name_zh' => '臀部叠叠乐'],
            ['name' => 'Outdoor Sex', 'name_zh' => '户外性爱'],
            ['name' => 'Male Plumber', 'name_zh' => '男水管工'],
            ['name' => 'Corset', 'name_zh' => '束腰'],
            ['name' => 'Nude Stockings', 'name_zh' => '裸露长袜'],
            ['name' => 'Slow Mo', 'name_zh' => '慢动作'],
            ['name' => 'Ass To Mouth', 'name_zh' => '臀部插入口中'],
            ['name' => 'Cowgirl Blowjob', 'name_zh' => '女上位口交'],
            ['name' => 'Nurse', 'name_zh' => '护士'],
            ['name' => 'Hospital', 'name_zh' => '医院'],
            ['name' => 'Doctor/Nurse', 'name_zh' => '医生/护士'],
            ['name' => 'Uniform', 'name_zh' => '制服'],
            ['name' => 'Employee', 'name_zh' => '员工'],
            ['name' => 'Rimjob', 'name_zh' => '舔肛'],
            ['name' => 'Shaved', 'name_zh' => '剃毛'],
            ['name' => 'Janitor', 'name_zh' => '清洁工'],
            ['name' => 'Police', 'name_zh' => '警察'],
            ['name' => 'Jean Shorts', 'name_zh' => '牛仔短裤'],
            ['name' => 'Teen18+', 'name_zh' => '青少年18+'],
            ['name' => 'Boots', 'name_zh' => '靴子'],
            ['name' => 'Colored Stockings', 'name_zh' => '彩色长袜'],
            ['name' => 'Latina', 'name_zh' => '拉丁裔女性'],
            ['name' => 'Facial - POV', 'name_zh' => '主观面部射精'],
            ['name' => 'Gaping', 'name_zh' => '扩张肛门'],
            ['name' => 'Police Station', 'name_zh' => '警察局'],
            ['name' => 'Pile Driving', 'name_zh' => '抬高插入'],
            ['name' => 'Tank Top', 'name_zh' => '背心'],
            ['name' => 'Gamer Girl', 'name_zh' => '游戏女孩'],
            ['name' => 'Girl Gamer', 'name_zh' => '女玩家'],
            ['name' => 'Living Room', 'name_zh' => '客厅'],
            ['name' => 'Girlfriend', 'name_zh' => '女友'],
            ['name' => 'Doggystyle - Lying', 'name_zh' => '主观后入式（躺姿）'],
            ['name' => 'Video Games', 'name_zh' => '电子游戏'],
            ['name' => 'Bikini', 'name_zh' => '比基尼'],
            ['name' => 'Oil', 'name_zh' => '油'],
            ['name' => 'Construction', 'name_zh' => '建筑工地'],
            ['name' => 'Jeans', 'name_zh' => '牛仔裤'],
            ['name' => 'Voyeur', 'name_zh' => '偷看'],
            ['name' => 'Bathroom', 'name_zh' => '浴室'],
            ['name' => 'Big Dick Worship', 'name_zh' => '大阴茎崇拜'],
            ['name' => 'Reverse Piledriver', 'name_zh' => '反向抬高插入'],
            ['name' => 'Cowboy Hat', 'name_zh' => '牛仔帽'],
            ['name' => 'Cowboy', 'name_zh' => '牛仔'],
            ['name' => 'Bondage', 'name_zh' => '束缚'],
            ['name' => 'Bar', 'name_zh' => '酒吧'],
            ['name' => 'Prison', 'name_zh' => '监狱'],
            ['name' => 'Dildo', 'name_zh' => '假阴茎'],
            ['name' => 'Handcuffs', 'name_zh' => '手铐'],
            ['name' => 'Asian Man', 'name_zh' => '亚洲男性'],
            ['name' => 'Geek / Nerd', 'name_zh' => '书呆子'],
            ['name' => 'Locker Room', 'name_zh' => '更衣室'],
            ['name' => 'Blowbang', 'name_zh' => '多人口交'],
            ['name' => 'Body Suit', 'name_zh' => '连体衣'],
            ['name' => 'Arab', 'name_zh' => '阿拉伯人'],
            ['name' => 'Cum on Pussy', 'name_zh' => '射在阴道内'],
            ['name' => 'Massage', 'name_zh' => '按摩'],
            ['name' => 'Washing', 'name_zh' => '清洗'],
            ['name' => 'Shower', 'name_zh' => '淋浴'],
            ['name' => 'Femdom', 'name_zh' => '女性支配'],
            ['name' => 'Alley', 'name_zh' => '小巷'],
            ['name' => 'Car', 'name_zh' => '汽车'],
            ['name' => 'MILF', 'name_zh' => '熟女'],
            ['name' => 'Japanese', 'name_zh' => '日本人'],
            ['name' => 'Reporter', 'name_zh' => '记者'],
            ['name' => 'Anal Creampie', 'name_zh' => '肛门内体内射精'],
            ['name' => 'Bathtub', 'name_zh' => '浴缸'],
            ['name' => 'Hotel Room', 'name_zh' => '酒店房间'],
            ['name' => 'Doggy 9', 'name_zh' => '狗式9'],
            ['name' => 'Pussy Stacking', 'name_zh' => '阴部叠叠乐'],
            ['name' => 'Fishnet Stockings', 'name_zh' => '渔网长袜'],
            ['name' => 'Husband', 'name_zh' => '丈夫'],
            ['name' => 'Male Mechanic', 'name_zh' => '男机修工'],
            ['name' => 'Wife', 'name_zh' => '妻子'],
            ['name' => 'Garage', 'name_zh' => '车库'],
            ['name' => 'Indian', 'name_zh' => '印度人'],
            ['name' => 'Leather', 'name_zh' => '皮革'],
            ['name' => 'Tall', 'name_zh' => '高个子'],
            ['name' => 'Leg Warmers', 'name_zh' => '腿套'],
            ['name' => 'Cuban', 'name_zh' => '古巴人'],
            ['name' => 'Strap-on', 'name_zh' => '绑带假阳具'],
            ['name' => 'Delivery Guy', 'name_zh' => '送货员'],
            ['name' => 'One-on-One', 'name_zh' => '一对一'],
            ['name' => 'Woman (20-29)', 'name_zh' => '20-29岁女性'],
            ['name' => 'Ball Gag', 'name_zh' => '球形口塞'],
            ['name' => 'Teddy', 'name_zh' => '泰迪内衣'],
            ['name' => 'Pinay', 'name_zh' => '菲律宾人'],
            ['name' => 'Gonzo', 'name_zh' => '冈佐'],
            ['name' => 'Pyjamas', 'name_zh' => '睡衣'],
            ['name' => 'Chinese', 'name_zh' => '中国人'],
            ['name' => 'POV', 'name_zh' => '主观镜头'],
            ['name' => 'Interactive Porn', 'name_zh' => '互动色情'],
            ['name' => 'Interactive', 'name_zh' => '互动'],
            ['name' => 'GILF', 'name_zh' => '老熟女'],
            ['name' => 'Bartender', 'name_zh' => '调酒师'],
            ['name' => 'Water', 'name_zh' => '水'],
            ['name' => 'Pool', 'name_zh' => '泳池'],
            ['name' => 'Brazilian', 'name_zh' => '巴西人'],
            ['name' => 'Sauna', 'name_zh' => '桑拿'],
            ['name' => 'Shorts', 'name_zh' => '短裤'],
            ['name' => 'Dominatrix', 'name_zh' => '女施虐者'],
            ['name' => 'Kinky', 'name_zh' => '恋物'],
            ['name' => 'Whip', 'name_zh' => '鞭子'],
            ['name' => 'Interview', 'name_zh' => '采访'],
            ['name' => 'Behind The Scenes', 'name_zh' => '幕后'],
            ['name' => 'Cuckold', 'name_zh' => '戴绿帽'],
            ['name' => 'Body Stockings', 'name_zh' => '连体丝袜'],
            ['name' => 'Hungarian', 'name_zh' => '匈牙利人'],
            ['name' => 'Sports', 'name_zh' => '运动'],
            ['name' => 'Masseuse', 'name_zh' => '按摩女'],
            ['name' => 'Handy Man', 'name_zh' => '勤杂工'],
            ['name' => 'Married', 'name_zh' => '已婚'],
            ['name' => 'Spoon BJ', 'name_zh' => '勺式口交'],
            ['name' => 'French Canadian', 'name_zh' => '法裔加拿大人'],
            ['name' => 'Native', 'name_zh' => '原住民'],
            ['name' => 'Group Sex', 'name_zh' => '多人性爱'],
            ['name' => 'Blindfold', 'name_zh' => '眼罩'],
            ['name' => 'Waiter', 'name_zh' => '服务员'],
            ['name' => 'Colombian', 'name_zh' => '哥伦比亚人'],
            ['name' => 'Stepmom', 'name_zh' => '继母'],
            ['name' => 'Stepson', 'name_zh' => '继子'],
            ['name' => 'Step Fantasy', 'name_zh' => '继亲幻想'],
            ['name' => 'Coach', 'name_zh' => '教练'],
            ['name' => 'Yoga', 'name_zh' => '瑜伽'],
            ['name' => 'Gym', 'name_zh' => '健身房'],
            ['name' => 'First Anal', 'name_zh' => '首次肛交'],
            ['name' => 'FIRST TIME ANAL on ZZ', 'name_zh' => 'ZZ第一次肛交'],
            ['name' => 'FIRST ZZ ANAL', 'name_zh' => 'ZZ首次肛交'],
            ['name' => 'Super Woman', 'name_zh' => '超级女人'],
            ['name' => 'Criminal', 'name_zh' => '罪犯'],
            ['name' => 'Cosplay', 'name_zh' => '角色扮演'],
            ['name' => 'Masks', 'name_zh' => '面具'],
            ['name' => 'Anal Winking', 'name_zh' => '肛门眨动'],
            ['name' => 'DP - Standing', 'name_zh' => '站立双插'],
            ['name' => 'Boyshorts', 'name_zh' => 'boy短裤'],
            ['name' => 'Sex Therapist', 'name_zh' => '性治疗师'],
            ['name' => 'Work From Home', 'name_zh' => '居家办公'],
            ['name' => 'Food', 'name_zh' => '食物'],
            ['name' => 'Wedding', 'name_zh' => '婚礼'],
            ['name' => 'Sun Hat', 'name_zh' => '太阳帽'],
            ['name' => 'Stripper', 'name_zh' => '脱衣舞娘'],
            ['name' => 'Strip Club', 'name_zh' => '脱衣俱乐部'],
            ['name' => 'Caught', 'name_zh' => '被抓现行'],
            ['name' => 'Curvy Woman', 'name_zh' => '曲线身材女性'],
            ['name' => 'Mom', 'name_zh' => '妈妈'],
            ['name' => 'Italian', 'name_zh' => '意大利人'],
            ['name' => 'Autofellatio', 'name_zh' => '自我口交'],
            ['name' => 'Brazzers Debut', 'name_zh' => 'Brazzers出道'],
            ['name' => 'Park', 'name_zh' => '公园'],
            ['name' => 'Domination', 'name_zh' => '支配'],
            ['name' => 'Stepdaughter', 'name_zh' => '继女'],
            ['name' => 'Latex', 'name_zh' => '乳胶'],
            ['name' => 'Streamer', 'name_zh' => '主播'],
            ['name' => 'Hairy Pussy', 'name_zh' => '毛茸茸的阴部'],
            ['name' => 'Independence Day', 'name_zh' => '独立日'],
            ['name' => '2 Part Series', 'name_zh' => '两集系列'],
            ['name' => 'Burglar', 'name_zh' => '闯入者'],
            ['name' => 'International', 'name_zh' => '国际'],
            ['name' => 'Slip', 'name_zh' => '内裤'],
            ['name' => 'Male Teacher', 'name_zh' => '男老师'],
            ['name' => 'First DP', 'name_zh' => '首次双插'],
            ['name' => 'Amateur', 'name_zh' => '业余'],
            ['name' => 'Male Boss', 'name_zh' => '男老板'],
            ['name' => 'Euro', 'name_zh' => '欧洲'],
            ['name' => 'Doctor', 'name_zh' => '医生'],
            ['name' => 'Glory Hole', 'name_zh' => '窥阴孔'],
            ['name' => 'Male Doctor', 'name_zh' => '男医生'],
            ['name' => 'Slow Dance', 'name_zh' => '慢舞'],
            ['name' => 'Standing 69', 'name_zh' => '站立69'],
            ['name' => 'Bridge', 'name_zh' => '拱桥'],
            ['name' => 'Swallow', 'name_zh' => '吞精'],
            ['name' => 'Sci-Fi', 'name_zh' => '科幻'],
            ['name' => 'Special Agent', 'name_zh' => '特工'],
            ['name' => 'Firefighter', 'name_zh' => '消防员'],
            ['name' => 'Waitress', 'name_zh' => '女服务员'],
            ['name' => 'Restaurant', 'name_zh' => '餐厅'],
            ['name' => 'Lesbian', 'name_zh' => '女同性恋'],
            ['name' => 'Russian', 'name_zh' => '俄罗斯人'],
            ['name' => 'Swingers', 'name_zh' => '换妻'],
            ['name' => 'Stepdad', 'name_zh' => '继父'],
            ['name' => 'Male to Female', 'name_zh' => '男变女'],
            ['name' => 'Guy fucks Trans', 'name_zh' => '与跨性别者性交'],
            ['name' => 'Trans', 'name_zh' => '跨性别'],
            ['name' => 'TransZZ', 'name_zh' => '跨性别ZZ'],
            ['name' => 'Pool Guy', 'name_zh' => '泳池工人'],
            ['name' => 'Tenants', 'name_zh' => '房客'],
            ['name' => 'Cameltoe', 'name_zh' => '骆驼趾'],
            ['name' => 'Step-brother', 'name_zh' => '继兄'],
            ['name' => 'Stepsister', 'name_zh' => '继妹'],
            ['name' => 'Masseur', 'name_zh' => '按摩师'],
            ['name' => 'Businessman', 'name_zh' => '商人'],
            ['name' => 'Moms', 'name_zh' => '妈妈们'],
            ['name' => 'Customer', 'name_zh' => '顾客'],
            ['name' => 'Male Prisoner', 'name_zh' => '男性囚犯'],
            ['name' => 'Cap', 'name_zh' => '帽子'],
            ['name' => 'Cougar', 'name_zh' => '老牛吃嫩草'],
            ['name' => 'Audio', 'name_zh' => '音频'],
            ['name' => 'Chef', 'name_zh' => '厨师'],
            ['name' => 'Fetish/BDSM', 'name_zh' => '恋物/BDSM'],
            ['name' => 'Double Vaginal', 'name_zh' => '双阴道'],
            ['name' => 'Skirt', 'name_zh' => '裙子'],
            ['name' => '25-34', 'name_zh' => '25-34岁'],
            ['name' => 'Detective', 'name_zh' => '侦探'],
            ['name' => 'Crime', 'name_zh' => '犯罪'],
            ['name' => 'Persian', 'name_zh' => '波斯人'],
            ['name' => 'E Girls', 'name_zh' => '性感女孩'],
            ['name' => 'Keiran', 'name_zh' => '凯伦'],
            ['name' => 'Pile Driver - POV', 'name_zh' => '主观抬高插入'],
            ['name' => 'Gardener', 'name_zh' => '园丁'],
            ['name' => 'Business Woman', 'name_zh' => '女商人'],
            ['name' => 'Security Guard', 'name_zh' => '保安'],
            ['name' => 'Secretary', 'name_zh' => '秘书'],
            ['name' => 'Photographer', 'name_zh' => '摄影师'],
            ['name' => 'Flight Attendant', 'name_zh' => '空乘'],
            ['name' => 'Cheerleader', 'name_zh' => '啦啦队员'],
            ['name' => '3 Part Series', 'name_zh' => '三集系列'],
            ['name' => '35 Plus', 'name_zh' => '35岁以上'],
            ['name' => 'Valentines Day', 'name_zh' => '情人节'],
            ['name' => 'Realtor', 'name_zh' => '房产经纪人'],
            ['name' => 'Black Friday', 'name_zh' => '黑色星期五'],
            ['name' => 'Mechanic', 'name_zh' => '机修工'],
            ['name' => 'Anal Fisting', 'name_zh' => '肛门拳交'],
            ['name' => 'Sweat', 'name_zh' => '出汗'],
            ['name' => 'Briefs', 'name_zh' => '平角内裤'],
            ['name' => 'Solo', 'name_zh' => '单人'],
            ['name' => 'Thanksgiving', 'name_zh' => '感恩节'],
            ['name' => 'Ski Mask', 'name_zh' => '滑雪面罩'],
            ['name' => 'New Years', 'name_zh' => '新年'],
            ['name' => 'Christmas', 'name_zh' => '圣诞节'],
            ['name' => 'Male Burglar', 'name_zh' => '男闯入者'],
            ['name' => 'First Gangbang', 'name_zh' => '首次群交'],
            ['name' => 'Boob play', 'name_zh' => '乳房玩法'],
            ['name' => 'Anal Beads', 'name_zh' => '肛门珠'],
            ['name' => 'Mixed', 'name_zh' => '混血'],
            ['name' => 'Male Firefighter', 'name_zh' => '男消防员'],
            ['name' => 'Sybian', 'name_zh' => 'Sybian骑乘器'],
            ['name' => 'Halloween', 'name_zh' => '万圣节'],
            ['name' => 'Anal Play', 'name_zh' => '肛门玩法'],
            ['name' => 'Strip Tease', 'name_zh' => '脱衣舞'],
            ['name' => 'Prisoner', 'name_zh' => '囚犯'],
            ['name' => 'Male Chef', 'name_zh' => '男厨师'],
            ['name' => 'Futanari', 'name_zh' => '扶他'],
            ['name' => 'VR', 'name_zh' => 'VR'],
            ['name' => 'Argentinian', 'name_zh' => '阿根廷人'],
            ['name' => 'Night Club', 'name_zh' => '夜总会'],
            ['name' => '4 Part Series', 'name_zh' => '四集系列'],
            ['name' => 'Babysitter', 'name_zh' => '保姆'],
            ['name' => 'Beach', 'name_zh' => '海滩'],
            ['name' => 'Reality', 'name_zh' => '真人秀'],
            ['name' => 'Boat', 'name_zh' => '船'],
            ['name' => 'Couples', 'name_zh' => '情侣'],
            ['name' => 'Plumber', 'name_zh' => '水管工'],
            ['name' => 'Doggystyle - Reverse', 'name_zh' => '反向狗式'],
            ['name' => 'Therapist', 'name_zh' => '治疗师'],
            ['name' => 'Gamer', 'name_zh' => '玩家'],
        ];

        $now = Carbon::now();
        $sortCounter = 10;

        // 使用 array_map 统一组装数据库结构
        $tagsToInsert = array_map(function ($item) use ($now, &$sortCounter) {
            // 使用 Str::slug 自动将英文名转换为 URL 友好的 slug
            // 如果遇到不支持的字符，默认转换为小写并用连字符替换空格
            $slug = Str::slug($item['name']);
            if (empty($slug)) {
                $slug = strtolower(str_replace([' ', '/', '(', ')', '+'], '-', $item['name']));
            }

            $mapped = [
                'name'              => $item['name'],
                'name_zh'           => $item['name_zh'],
                'slug'              => $slug,
                'description'       => '此标签包含与' . $item['name_zh'] . '相关的视频内容。',
                'avatar'            => "/storage/tags/{$slug}_square.jpg",
                'avatar_vertical'   => "/storage/tags/{$slug}_vertical.jpg",
                'avatar_horizontal' => "/storage/tags/{$slug}_horizontal.jpg",
                // 模拟一些初始的统计数据
                'video_num'         => rand(10, 500),
                'follow_num'        => rand(100, 2000),
                'photo_num'         => rand(0, 100),
                'sort'              => $sortCounter,
                'created_at'        => $now,
                'updated_at'        => $now,
            ];

            // 每次循环排序值增加 10
            $sortCounter += 10;

            return $mapped;
        }, $data);

        // 数据量较大（约 260 条），使用 array_chunk 将其切片分批插入，防止 SQL 语句过长
        $chunks = array_chunk($tagsToInsert, 100);
        foreach ($chunks as $chunk) {
            DB::table('tags')->insert($chunk);
        }
    }
}
